### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by amilajack** [evanw/glfx.js#34]
@evanw I am willing to offer long term and active support for this project if that is fine with you.

I'm considering:

- Refactoring
- Offering test coverage
- Providing support for modern node versions
- Improving docs my providing installation steps

**Comment by fesor** [comment]
@amilajack may I help?

**Comment by amilajack** [comment]
@fesor sure! I'm just waiting for approval from @evanw. I don't want to make a big PR if the project isn't active anymore.

**Comment by nuxodin** [comment]
Last reaction from the author @evanw is from 2013, i dont think he is interested or has time to continue with this project.
I think its better to start a new project.

**Comment by okcoker** [comment]
@amilajack did you end up starting a new project from this?

**Comment by amilajack** [comment]
@okcoker no i didn't
