### ISSUE TITLE
one iphone safair make an image bug?

### ISSUE THREAD

**Issue by leafx** [evanw/glfx.js#36]
hi,

on my safair,
toDataURL() got data be image src attr,
but, its had overturn

who can give a suggest to fix it.

thanks

**Comment by NicholaAlkhouri** [comment]
Hello, i have the same problem too, any help please.

**Comment by leafx** [comment]
I just overturn the final image on safair,it's may be webgl bug, so you can try it by this way.

**Comment by NicholaAlkhouri** [comment]
Thats exactly what i'm doing, i'm using matrixWrap to flip the image vertically in case of safari browser
`fxCanvas.draw(texture).matrixWarp([[1,0],[0,-1]], false, true);`

**Comment by leafx** [comment]
So beautiful code ! Thanks.
