### ISSUE TITLE
bulgePinch in JavaScript

### ISSUE THREAD

**Issue by akinuri** [evanw/glfx.js#37]
Can someone write a basic JS version of the `bulgePinch`? What I really need is just the pinch effect. I have no WebGL knowledge, so I can't write it on my own.

I've also looked at the source code of Gimp for the same effect, but again, I have no C knowledge.

[akinuri/canvas-pinch](https://github.com/akinuri/canvas-pinch)

**Comment by malipetek** [comment]
I was looking around to extract that part also. [This ](http://chenxing.name/fun/imgwarp-js/)is also promising but bulge pinch is so smooth.

**Comment by akinuri** [comment]
I, now, know how this works. See [Pinch/pucker an image in canvas](https://stackoverflow.com/questions/33402497/pinch-pucker-an-image-in-canvas).
