### ISSUE TITLE
Firefox Showing Black Empty Canvas

### ISSUE THREAD

**Issue by duckzland** [evanw/glfx.js#53]
When using the latest firefox version 79, the canvas element is just showing a black image, while it is working fine under chrome.

The browser throwing warning:
 
WebGL warning: checkFramebufferStatus: Using format enabled by implicitly enabled extension: WEBGL_color_buffer_float. For maximal portability enable it explicitly.

Snippet code to build the fx canvas code which is working fine at chrome
```
let img = new Image();
let canvas = fx.canvas();

img.onload = () => {
     let texture = canvas.texture(img);
     canvas.draw(texture);
     canvas.update();
}

// Base64 is base64 encoded image
img.src = base64;
```

Is there a way to circumvent the problem?

Thanks in advance

**Comment by Axel-Jacobsen** [comment]
For the future: I got the same warning. The warning is gone with

```
let canvas = fx.canvas()
let texture = canvas.texture(img)
texture._.gl.getExtension('WEBGL_color_buffer_float')
```

For Duckzland, I am not sure what the issue is. It has been two years, so maybe you've moved past the issue?

**Comment by duckzland** [comment]
for me it was firefox problem, after reporting it to firefox dev's they fixed the problem, havent retried it again now

**Comment by Axel-Jacobsen** [comment]
OK interesting - I am/was on Firefox Developer Edition 98, perhaps I have some experimental feature on.

**Comment by duckzland** [comment]
firefox's dev told me video card might also cause the problem. I'm not sure about it though
